apiRules:
- exclude:
    uidRegex: ^Lean\.Touch$
    type: Namespace
- exclude:
    uidRegex: ^UnityEngine\.Networking\.NetworkBehaviour
    type: Type
- exclude:
    uidRegex: ^UnityEngine\.MonoBehaviour
    type: Type
- exclude:
    uidRegex: ^UnityEngine\.Behaviour
    type: Type
- exclude:
    uidRegex: ^UnityEngine\.Component
    type: Type
- exclude:
    uidRegex: ^UnityEngine\.Object
    type: Type
- exclude:
    uidRegex: ^System\.Object
    type: Type